# encoding: utf-8

namespace :db do
  task :require_config do
    require 'halfmoon/config'
    require_relative './app/config/config'
  end

  task :require_model do
    require 'halfmoon/db'
    require 'halfmoon/migration'
  end

  desc 'Migrationファイルを作成'
  task :create, ['name'] => [:require_config] do |_, args|
    file Config[:db_name] do
    end
  end

  desc 'MigrationファイルからDBを操作'
  task :migration, ['method', 'table'] => [:require_config, :require_model] do |_, args|
    Config.add :root, File.expand_path(File.dirname(__FILE__))
    require_relative "./app/db/migration/#{args[:table]}_migration.rb"
    klass = "#{args[:table].capitalize}Migration"
    if args[:method] == 'create'
      Kernel.const_get(klass).new.create
    elsif args[:method] == 'change'
      Kernel.const_get(klass).new.change
    end
  end
end
