# encoding: utf-8

namespace :db do
  task :require_config do
    require 'halfmoon/config'
    require_relative './app/config/config'
  end

  task :require_model do
    require 'halfmoon/db'
    require 'halfmoon/migration'
  end

  desc 'MigrationファイルからDBを操作'
  task :migration, ['method', 'table'] => [:require_config, :require_model] do |_, args|
    Config.add :root, File.expand_path(File.dirname(__FILE__))
    require_relative "./app/db/migration/#{args[:table]}_migration.rb"
    klass = "#{args[:table].capitalize}Migration"
    begin
      Kernel.const_get(klass).new.send(args[:method].to_sym)
    rescue NoMethodError
      puts "undefined method `#{args[:method]}` for #{klass}."
      exit(1)
    rescue NameError
      puts 'クラスが存在しません。クラス名はテーブル名の単数形です。'
      exit(1)
    end
  end
end
